"""empty message

Revision ID: 085d7a4ef671
Revises: ec420759d18f
Create Date: 2026-05-10 08:41:34.355864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085d7a4ef671'
down_revision = 'ec420759d18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instalment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('down_payment', sa.Float(), nullable=True),
    sa.Column('remaining_amount', sa.Float(), nullable=True),
    sa.Column('number_of_installments', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('paid_installments', sa.Integer(), nullable=True),
    sa.Column('missed_payments', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instalment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instalment_plans_plan_id'), ['plan_id'], unique=True)

    op.create_table('instalment_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('late_fee', sa.Float(), nullable=True),
    sa.Column('late_fee_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['instalment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instalment_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instalment_payments_payment_id'), ['payment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalment_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instalment_payments_payment_id'))

    op.drop_table('instalment_payments')
    with op.batch_alter_table('instalment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instalment_plans_plan_id'))

    op.drop_table('instalment_plans')
    # ### end Alembic commands ###
