"""empty message

Revision ID: 09e22ec62bb6
Revises: d685c625ede2
Create Date: 2026-05-28 11:15:19.249444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e22ec62bb6'
down_revision = 'd685c625ede2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_id', sa.String(length=50), nullable=False))
        batch_op.drop_index('ix_notifications_notifications_id')
        batch_op.create_index(batch_op.f('ix_notifications_notification_id'), ['notification_id'], unique=True)
        batch_op.drop_column('notifications_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_id'))
        batch_op.create_index('ix_notifications_notifications_id', ['notifications_id'], unique=False)
        batch_op.drop_column('notification_id')

    # ### end Alembic commands ###
