"""empty message

Revision ID: 0d0c02acce19
Revises: 2f63064ecdef
Create Date: 2026-05-26 09:11:55.329288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0c02acce19'
down_revision = '2f63064ecdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_otp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reset_otp_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_otp_expiry')
        batch_op.drop_column('reset_otp')

    # ### end Alembic commands ###
