"""empty message

Revision ID: 28f7ce62c5a2
Revises: 6c4a255f9915
Create Date: 2026-05-24 17:42:24.823551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f7ce62c5a2'
down_revision = '6c4a255f9915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('payout_amount')

    # ### end Alembic commands ###
