"""empty message

Revision ID: 2f63064ecdef
Revises: 7253d5a4a37d
Create Date: 2026-05-26 08:02:31.356121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f63064ecdef'
down_revision = '7253d5a4a37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_website_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_website_key', ['website'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
