"""empty message

Revision ID: 6f54c184794a
Revises: d53fab028a5d
Create Date: 2026-05-21 06:48:03.698810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f54c184794a'
down_revision = 'd53fab028a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('remaining_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_balance', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
