"""empty message

Revision ID: 763bd2284598
Revises: d3463526b055
Create Date: 2026-05-03 08:26:37.454321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763bd2284598'
down_revision = 'd3463526b055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agree', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('agree')

    # ### end Alembic commands ###
