"""empty message

Revision ID: 7adf3644fd2c
Revises: f8a5d2e3c7aa
Create Date: 2026-09-27 14:43:07.352742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adf3644fd2c'
down_revision = 'f8a5d2e3c7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=140), nullable=False),
    sa.Column('identifier', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_subject'), ['subject'], unique=False)

    op.create_table('devices_seen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('flags', sa.String(length=200), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'user_id', name='uq_devices_seen_device_user')
    )
    with op.batch_alter_table('devices_seen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_seen_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_seen_user_id'), ['user_id'], unique=False)

    op.create_table('fraud_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('fraud_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_signals_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_signals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_signals_user_id'), ['user_id'], unique=False)

    op.create_table('identity_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('product', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('id_type', sa.String(length=40), nullable=True),
    sa.Column('id_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_status', sa.String(length=20), nullable=True),
    sa.Column('provider_message', sa.String(length=255), nullable=True),
    sa.Column('name_match', sa.Boolean(), nullable=True),
    sa.Column('dob_match', sa.Boolean(), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('identity_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_checks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_checks_user_id'), ['user_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('authorization_code', sa.String(length=100), nullable=False),
    sa.Column('signature', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('card_type', sa.String(length=30), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('exp_month', sa.String(length=2), nullable=True),
    sa.Column('exp_year', sa.String(length=4), nullable=True),
    sa.Column('reusable', sa.Boolean(), nullable=True),
    sa.Column('autopay_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_signature'), ['signature'], unique=False)

    op.create_table('pii_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pii_access_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pii_access_log_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pii_access_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pii_access_log_user_id'), ['user_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('pay_in_4_dp_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('limit_multiplier', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outstanding', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extended_plans_eligible', sa.Boolean(), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('inputs', sa.Text(), nullable=True),
    sa.Column('rules_version', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_user_id'), ['user_id'], unique=False)

    op.create_table('setting_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setting_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setting_changes_setting_key'), ['setting_key'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('fees_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('clawbacks_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('net_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hold_reason', sa.String(length=255), nullable=True),
    sa.Column('transfer_reference', sa.String(length=64), nullable=True),
    sa.Column('transfer_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_reference')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_settlement_id'), ['settlement_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_settlements_status'), ['status'], unique=False)

    op.create_table('payment_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_by_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['used_by_order_id'], ['purchase_orders.id'], name='fk_payment_links_used_by_order_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_links_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_links_token'), ['token'], unique=True)

    op.create_table('settlement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('gross_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('fee_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('net_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['instalment_plans.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_lines_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_lines_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_lines_settlement_id'), ['settlement_id'], unique=False)

    op.create_table('instalment_part_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount_pesewas', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['instalment_payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['instalment_plans.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('instalment_part_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instalment_part_payments_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instalment_part_payments_plan_id'), ['plan_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['instalment_payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['instalment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_plan_id'), ['plan_id'], unique=False)

    op.create_table('message_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('to_address', sa.String(length=50), nullable=True),
    sa.Column('template', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['instalment_payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['instalment_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('message_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_outbox_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_outbox_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_outbox_user_id'), ['user_id'], unique=False)

    op.create_table('payment_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['instalment_payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['instalment_plans.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_claims_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_claims_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_claims_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_claims_status'), ['status'], unique=False)

    op.create_table('payment_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('gateway_response', sa.String(length=255), nullable=True),
    sa.Column('paid_amount_pesewas', sa.BigInteger(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['instalment_payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['instalment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_intents_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_intents_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_intents_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_intents_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_intents_reference'), ['reference'], unique=True)

    op.create_table('deferments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=True),
    sa.Column('fee_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('original_due_date', sa.DateTime(), nullable=False),
    sa.Column('new_due_date', sa.DateTime(), nullable=True),
    sa.Column('moved_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['payment_intents.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['instalment_payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['instalment_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id')
    )
    with op.batch_alter_table('deferments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deferments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferments_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferments_plan_id'), ['plan_id'], unique=False)

    with op.batch_alter_table('instalment_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_fee_stage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('second_late_fee_applied_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('original_due_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('instalment_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_past_due', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dpd_bucket', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('collection_stage', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('charged_off_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paused_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paused_reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('down_payment_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('down_payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('down_payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('down_payment_paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('refund_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('refund_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_link_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('risk_assessment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('terms_version', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'transactions', ['transaction_id'], ['id'])
        batch_op.create_foreign_key(None, 'payment_links', ['payment_link_id'], ['id'])
        batch_op.create_foreign_key(None, 'risk_assessments', ['risk_assessment_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('employment_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('salary_paid_to_bank', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('salary_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('risk_tier', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('credit_limit_override', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('limit_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('settlement_period_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payout_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payout_bank_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('paystack_recipient_code', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('payout_details_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payout_hold_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('employment_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('employment_verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employment_verification_method', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('employment_verification_note', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('admin_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('merchant_fee_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reset_otp_attempts', sa.Integer(), nullable=True))
        batch_op.drop_constraint('users_ref_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_ref_phone_key', ['ref_phone'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('reset_otp_attempts')
        batch_op.drop_column('merchant_fee_tier')
        batch_op.drop_column('admin_level')
        batch_op.drop_column('employment_verification_note')
        batch_op.drop_column('employment_verification_method')
        batch_op.drop_column('employment_verified_by')
        batch_op.drop_column('employment_verified_at')
        batch_op.drop_column('payout_hold_until')
        batch_op.drop_column('payout_details_updated_at')
        batch_op.drop_column('paystack_recipient_code')
        batch_op.drop_column('payout_bank_code')
        batch_op.drop_column('payout_method')
        batch_op.drop_column('settlement_period_days')
        batch_op.drop_column('limit_updated_at')
        batch_op.drop_column('credit_limit_override')
        batch_op.drop_column('credit_limit')
        batch_op.drop_column('risk_tier')
        batch_op.drop_column('salary_verified')
        batch_op.drop_column('salary_paid_to_bank')
        batch_op.drop_column('employment_start_date')
        batch_op.drop_column('monthly_salary')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('terms_accepted_at')
        batch_op.drop_column('terms_version')
        batch_op.drop_column('risk_assessment_id')
        batch_op.drop_column('payment_link_id')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('refund_reference')
        batch_op.drop_column('refund_status')
        batch_op.drop_column('down_payment_paid_at')
        batch_op.drop_column('down_payment_method')
        batch_op.drop_column('down_payment_reference')
        batch_op.drop_column('down_payment_status')

    with op.batch_alter_table('instalment_plans', schema=None) as batch_op:
        batch_op.drop_column('paused_reason')
        batch_op.drop_column('paused_at')
        batch_op.drop_column('charged_off_at')
        batch_op.drop_column('collection_stage')
        batch_op.drop_column('dpd_bucket')
        batch_op.drop_column('days_past_due')

    with op.batch_alter_table('instalment_payments', schema=None) as batch_op:
        batch_op.drop_column('original_due_date')
        batch_op.drop_column('second_late_fee_applied_date')
        batch_op.drop_column('late_fee_stage')

    with op.batch_alter_table('deferments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deferments_plan_id'))
        batch_op.drop_index(batch_op.f('ix_deferments_payment_id'))
        batch_op.drop_index(batch_op.f('ix_deferments_customer_id'))

    op.drop_table('deferments')
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_intents_reference'))
        batch_op.drop_index(batch_op.f('ix_payment_intents_plan_id'))
        batch_op.drop_index(batch_op.f('ix_payment_intents_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_intents_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_intents_customer_id'))

    op.drop_table('payment_intents')
    with op.batch_alter_table('payment_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_claims_status'))
        batch_op.drop_index(batch_op.f('ix_payment_claims_plan_id'))
        batch_op.drop_index(batch_op.f('ix_payment_claims_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_claims_customer_id'))

    op.drop_table('payment_claims')
    with op.batch_alter_table('message_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_outbox_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_outbox_status'))
        batch_op.drop_index(batch_op.f('ix_message_outbox_plan_id'))

    op.drop_table('message_outbox')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_plan_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_payment_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('instalment_part_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instalment_part_payments_plan_id'))
        batch_op.drop_index(batch_op.f('ix_instalment_part_payments_payment_id'))

    op.drop_table('instalment_part_payments')
    with op.batch_alter_table('settlement_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_lines_settlement_id'))
        batch_op.drop_index(batch_op.f('ix_settlement_lines_plan_id'))
        batch_op.drop_index(batch_op.f('ix_settlement_lines_merchant_id'))

    op.drop_table('settlement_lines')
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_links_token'))
        batch_op.drop_index(batch_op.f('ix_payment_links_merchant_id'))

    op.drop_table('payment_links')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_status'))
        batch_op.drop_index(batch_op.f('ix_settlements_settlement_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_merchant_id'))

    op.drop_table('settlements')
    with op.batch_alter_table('setting_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setting_changes_setting_key'))

    op.drop_table('setting_changes')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_user_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('pii_access_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pii_access_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_pii_access_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_pii_access_log_admin_id'))

    op.drop_table('pii_access_log')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_signature'))
        batch_op.drop_index(batch_op.f('ix_payment_methods_customer_id'))

    op.drop_table('payment_methods')
    with op.batch_alter_table('identity_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_checks_user_id'))
        batch_op.drop_index(batch_op.f('ix_identity_checks_status'))

    op.drop_table('identity_checks')
    with op.batch_alter_table('fraud_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_signals_user_id'))
        batch_op.drop_index(batch_op.f('ix_fraud_signals_status'))
        batch_op.drop_index(batch_op.f('ix_fraud_signals_code'))

    op.drop_table('fraud_signals')
    with op.batch_alter_table('devices_seen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_seen_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_seen_device_id'))

    op.drop_table('devices_seen')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_subject'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_kind'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_identifier'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
