"""empty message

Revision ID: 89dfae1d0197
Revises: cd0e335aff5e
Create Date: 2026-05-19 14:54:44.189014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dfae1d0197'
down_revision = 'cd0e335aff5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('specifications')
        batch_op.drop_column('cost_price')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('compare_price')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_keywords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_keywords', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('compare_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('seo_title', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cost_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('specifications', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
