"""empty message

Revision ID: b4bf9b7e6155
Revises: 4c9de7ba5609
Create Date: 2026-05-16 13:10:38.282170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bf9b7e6155'
down_revision = '4c9de7ba5609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('transaction_alerts', sa.Boolean(), nullable=True),
    sa.Column('settlement_alerts', sa.Boolean(), nullable=True),
    sa.Column('dispute_alerts', sa.Boolean(), nullable=True),
    sa.Column('promotional_emails', sa.Boolean(), nullable=True),
    sa.Column('newsletter', sa.Boolean(), nullable=True),
    sa.Column('daily_summary', sa.Boolean(), nullable=True),
    sa.Column('weekly_report', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
