"""empty message

Revision ID: bd06b9cb06b1
Revises: bd6ada3d056e
Create Date: 2026-05-24 17:36:24.304125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd06b9cb06b1'
down_revision = 'bd6ada3d056e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('payout_amount')

    # ### end Alembic commands ###
