"""empty message

Revision ID: bd6ada3d056e
Revises: e4caff1124c9
Create Date: 2026-05-24 13:10:39.870266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6ada3d056e'
down_revision = 'e4caff1124c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalment_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_fee_applied_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalment_payments', schema=None) as batch_op:
        batch_op.drop_column('late_fee_applied_date')

    # ### end Alembic commands ###
