"""empty message

Revision ID: bdc8c2fa6e05
Revises: 1d6fe4decf1e
Create Date: 2026-05-05 07:56:14.005301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc8c2fa6e05'
down_revision = '1d6fe4decf1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tax_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('business_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_products', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_sales', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('agree',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('agree',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('verified')
        batch_op.drop_column('rating')
        batch_op.drop_column('total_sales')
        batch_op.drop_column('total_products')
        batch_op.drop_column('description')
        batch_op.drop_column('website')
        batch_op.drop_column('business_email')
        batch_op.drop_column('business_phone')
        batch_op.drop_column('business_address')
        batch_op.drop_column('tax_id')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('business_type')

    # ### end Alembic commands ###
