"""empty message

Revision ID: cd0e335aff5e
Revises: da6b62625229
Create Date: 2026-05-19 14:24:43.604512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0e335aff5e'
down_revision = 'da6b62625229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('installment_available')
        batch_op.drop_column('min_installment_months')
        batch_op.drop_column('max_installment_months')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_installment_months', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('min_installment_months', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('installment_available', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
