"""empty message

Revision ID: d653b264f0a0
Revises: f05d4077e386
Create Date: 2026-05-05 15:06:25.570242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd653b264f0a0'
down_revision = 'f05d4077e386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('merchant_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['merchant_id'])
        batch_op.create_unique_constraint(None, ['customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('merchant_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
