"""empty message

Revision ID: eed7237f7c95
Revises: d653b264f0a0
Create Date: 2026-05-05 15:08:55.797623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed7237f7c95'
down_revision = 'd653b264f0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('merchant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_customer_id'), ['customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_merchant_id'), ['merchant_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_user_customer_id'))
        batch_op.drop_column('merchant_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
