"""empty message

Revision ID: f05d4077e386
Revises: bdc8c2fa6e05
Create Date: 2026-05-05 15:04:08.891693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05d4077e386'
down_revision = 'bdc8c2fa6e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('merchant_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['customer_id'])
        batch_op.create_unique_constraint(None, ['merchant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('merchant_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
